### PR TITLE
Incident display on mobile

### PR DESCRIPTION
**Pull request by abdulmannans**
Incident display on mobile #88

### CODE REVIEW

**Comment by abdulmannans** [comment]
Screenshot 2024-10-05 at 2 05 58 AM
Screenshot 2024-10-05 at 2 06 17 AM

**Comment by jbrooksuk** [comment]
This is a great start, thanks!

I think everything should be left aligned on mobile, with the title, timestamp and text spanning the full width. Can you make those changes too?

**Comment by abdulmannans** [comment]
Sure. I will make that changes

**Comment by jbrooksuk** [comment]
I've made some tweaks to this now.

CleanShot 2024-10-05 at 16 57 42@2x

CleanShot 2024-10-05 at 16 57 57@2x

**Comment by abdulmannans** [comment]
Sorry @jbrooksuk I was busy with local meetup we had

**Comment by jbrooksuk** [comment]
All good, thanks for kicking this off!

**Pull request merged**
