### PR TITLE
[WIP] Manage Localization Settings

### LINKED ISSUE #65: Localization Settings
In Cachet 2.x we offer localization settings:

image

We need to make sure that these are available settings.

The dashboard should make it clear that to change the timezone, you should change the `APP_TIMEZONE` environment key.

Formatting of dates and timestamps should then use the given format (if set).

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes #65

I'm still considering whether this is the right path or not. Does it make sense to have a "global" setting for date / timestamp formatting, or should it be possible to change individual settings - this could be more tedious though.

CleanShot 2024-10-04 at 13 44 21

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Also, I kind of think it'd be better to show timestamps in whatever the browser dictates as the best format for the visitor's locale...

**Comment by spoyntersmith** [comment]
> Also, I kind of think it'd be better to show timestamps in whatever the browser dictates as the best format for the visitor's locale...

Agree with this, as it means a user doesn't need to set the preference it it's not the same as the default, it will automatically follow their browser locale and preference with no effort.

I think Manage Localization would be more useful for language settings or something else like display timezone... 🤔

**Comment by jbrooksuk** [comment]
Agreed! I'm going to close this PR and we can pick this up again.

@spoyntersmith do you fancy implementing the changes? 🎃

**Comment by spoyntersmith** [comment]
> Agreed! I'm going to close this PR and we can pick this up again.
> 
> @spoyntersmith do you fancy implementing the changes? 🎃

Happy to! Could you add an issue and I will take a look 💪

**Comment by jbrooksuk** [comment]
@spoyntersmith https://github.com/cachethq/core/issues/124

**Pull request closed without merging**
