### PR TITLE
Add DarkMode and Theme support #68 #78

### PR DESCRIPTION
**Pull request by steffjenl**
Edit screen:
image

Statuspage:
image

I think we must add more colors to change

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Great start! I think we should store RGBA colors for the status page themes, it's more versatile. 

I'm on my phone at the moment, but will check this out for a full review soon!

**Comment by jbrooksuk** [comment]
Note, assets don't need to be committed manually anymore.

**Comment by steffjenl** [comment]
> Note, assets don't need to be committed manually anymore.

Compile Assets commit is coming from GitHub actions not from me.

**Comment by steffjenl** [comment]
> Great start! I think we should store RGBA colors for the status page themes, it's more versatile.
> 
> I'm on my phone at the moment, but will check this out for a full review soon!

I have changed the PR to RGBA and added font setting

**Comment by steffjenl** [comment]
image

image

**Comment by jbrooksuk** [comment]
Ah, thanks! I've made the assets only compile on `main` now.

**Comment by steffjenl** [comment]
@jbrooksuk fixed merge conflicts with main

**Review by jbrooksuk — CHANGES_REQUESTED** [review]
Do you think we need to switch to using a customizable color palette so that we use `danger` etc?

**Comment by steffjenl** [comment]
> resources/views/components/cachet.blade.php

You mean, dark, light, system and custom and with custom you get the custom colors?

**Comment by jbrooksuk** [comment]
@steffjenl I wonder whether we could simplify this to use Filament's own `Color` class? We just store the `primary` color and then generate the shades for that? We'd need to change the Tailwind config to read from the CSS variables instead though. Maybe that's a lot of work?

**Comment by steffjenl** [comment]
> @steffjenl I wonder whether we could simplify this to use Filament's own `Color` class? We just store the `primary` color and then generate the shades for that? We'd need to change the Tailwind config to read from the CSS variables instead though. Maybe that's a lot of work?

You mean the colors setting in Filament? and add those six colors ?

`    return $panel
        // ...
        ->colors([
            'danger' => Color::Rose,
            'gray' => Color::Gray,
            'info' => Color::Blue,
            'primary' => Color::Indigo,
            'success' => Color::Emerald,
            'warning' => Color::Orange,
        ]);`

**Comment by jbrooksuk** [comment]
I've replaced this PR with https://github.com/cachethq/core/pull/143.

The only thing we could add is the theme switched.

**Pull request closed without merging**
