### PR TITLE
Add date selector on incident timeline #99

### PR DESCRIPTION
**Pull request by steffjenl**
Add date selector on incident timeline #99

image

Preview

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Thanks @steffjenl! I wonder whether we should provide a range selector instead, that's set to the duration of the days setting? Is that weird? I'm not sure I'm a massive fan of having two inputs.

**Comment by steffjenl** [comment]
@jbrooksuk it is one input, the right input is disabled so we respect the durations of days settings. I have only changed to an input to make it the same look and feel.

**Comment by steffjenl** [comment]
Or do you want more like https://filamentphp.com/plugins/malzariey-daterangepicker-filter ? I personly does not like this type of input on public forms.

**Comment by jbrooksuk** [comment]
Yeah, I do prefer a range picker. It allows you to really control how much data you want to display, though I don't think we need options for "Last 30 Days" etc.

What's your reason for not liking them on public forms?

Also, if we keep your current implementation, can we remove one of the duplicate calendar icons?

CleanShot 2024-10-14 at 08 54 30@2x

**Comment by steffjenl** [comment]
image

**Pull request merged**
