### PR TITLE
Make the UUID visible for incidents

### LINKED ISSUE #73: Incident Dashboard Improvements
There's a few improvements to make around the incident dashboard story:

1. The incident UUID value should be shown somewhere when viewing an incident.
2. There should be a link to the incident on the status page.

### PR DESCRIPTION
**Pull request by ash-jc-allen**
Hey @jbrooksuk! This PR is an attempt to add some features mentioned in #73. I'm still really new to Cachet and Filament, so I do apologise if I've completely misunderstood what's needed and done it wrong. If that's the case, gimme a shout, and I'll get this PR updated right away 😄

This PR proposes that the UUID is now available in the Filament dashboard (at the bottom of the right hand panel):

Screenshot 2024-10-04 at 18 52 03

It also adds the incident UUID to the incidents on the public-facing pages (in the bottom right of the incident cards):

Screenshot 2024-10-04 at 18 51 27

Screenshot 2024-10-04 at 18 51 35

And if the user is authenticated, then a "View in Dashboard" link will be displayed that takes the user directly to the "edit" page in the Filament dashboard. This link is in the bottom right of the incident card again:

Screenshot 2024-10-04 at 18 52 46
Screenshot 2024-10-04 at 18 52 54

I've not committed my `manifest.json` and `public/build/assets/cache.XXXX.css` files, but I noticed they're being tracked in GIt. Would you like me to commit them and push them up? 😄

Closes #73

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Looking good, @ash-jc-allen, thanks!

There are a couple of changes I'd like to make:

1. The UUID doesn't need to be shown in the incident timeline.
2. The incident index within the dashboard should have a link to the incident page.

**Comment by ash-jc-allen** [comment]
Sweet!

Just to double check something. Am I right in guessing you don't want the UUID in either of the public facing pages at all? Or do you still want it on the "show" page (`/status/incidents/d3f05743-7b8c-4ecd-b464-567f35547a35`)?

And is this the kind of thing you're thinking of for the link in the dashboard direct to the incident? 🙂

Screenshot 2024-10-05 at 13 45 28

**Comment by jbrooksuk** [comment]
Looks good to me. I'd maybe show the UUID in the incident page, but it should be very secondary information?

**Comment by jbrooksuk** [comment]
@ash-jc-allen sorry about the conflicts 😅 Should be easily resolvable as we shouldn't show the UUID on the incident view anyway.

**Comment by ash-jc-allen** [comment]
Hey @jbrooksuk! It's totally cool about the conflicts (they were nice and easy to fix 😄). I've tried having another crack at this, so hopefully it's a bit closer to what you were looking for 🤞

I've removed the UUID from the index page, but the "View in dashboard" button is still there:

Screenshot 2024-10-06 at 22 37 40

On the show page, I've moved the UUID to the bottom of the page (on the right hand side):

Screenshot 2024-10-06 at 22 35 42

Please gimme a shout if you'd like me to make any changes 😄

**Comment by ash-jc-allen** [comment]
Love that button change with the icon! And I didn't know about the `auth` Blade directive, so I'm gonna have to remember that one for the future 😄

**Pull request merged**
